name: SkriptLanguage
author: Jake
version: 1.2.0
main: me.jake.SkriptLanguage
api-version: 1.19
depend: [Skript]
commands:
  skriptlanguage:
    description: SkriptLanguage reload command
    usage: /skriptlanguage
    permission: skriptlanguage.commands.reload